#!/usr/bin/env bash
# Configure my domain zone:
# www --> 141562-lb-01 54.83.160.184
# web-01 --> 141562-web-01 52.91.149.165
# web-02 --> 141562-web-02 100.26.237.89

# -- To be evaluated --
# domain_information () {
#     line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#     echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
# }

# if [ "$#" == 1 ]
# then
#   domain_information "$1" "www"
#   domain_information
