#!/usr/bin/env bash
# Configure my domain zone:
# www --> 122036-lb-01 34.229.70.24
# web-01 --> 122036-web-01 18.210.15.149
# web-02 --> 122036-web-02 34.229.70.214

# -- To be evaluated --
# domain_information () {
#     line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
#     echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
# }

# if [ "$#" == 1 ]
# then
#   domain_information "$1" "www"
#   domain_information
